In [18]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
import warnings

%matplotlib inline
%config InlineBackend.figure_format = 'retina'

warnings.filterwarnings('ignore')
plt.rcParams["figure.figsize"] = (16,8)
plt.rcParams['axes.unicode_minus'] = False
plt.rc('font', family='Malgun Gothic')

In [19]:
gw =  pd.read_csv("C:/Users/keogu/Desktop/빅데이터 자료분석/weather/강원도.csv",encoding="cp949",parse_dates=['일시'])

In [20]:
gw

,지점,지점명,일시,평균기온(°C),최저기온(°C),최고기온(°C),일강수량(mm),평균 이슬점온도(°C),평균 상대습도(%),합계 일사량(MJ/m2),일 최심적설(cm),평균 지면온도(°C)
0,90,속초,2014-01-01,6.6,4.1,8.9,NaN,-9.3,31.3,NaN,NaN,1.8
1,90,속초,2014-01-02,4.0,-0.3,7.0,NaN,-11.5,31.9,NaN,NaN,0.1
2,90,속초,2014-01-03,6.6,2.4,9.4,NaN,-6.5,40.0,NaN,NaN,1.6
3,90,속초,2014-01-04,1.2,0.0,3.8,7.4,-1.0,87.4,NaN,6.0,0.2
4,90,속초,2014-01-05,0.4,-2.0,2.7,0.0,-1.1,90.0,NaN,6.0,0.1
...,...,...,...,...,...,...,...,...,...,...,...,...
39045,217,정선군,2021-10-27,10.6,4.8,19.5,0.0,4.7,72.6,NaN,NaN,12.5
39046,217,정선군,2021-10-28,9.4,1.9,19.7,NaN,3.2,70.1,NaN,NaN,10.9
39047,217,정선군,2021-10-29,8.6,3.3,18.4,NaN,3.7,75.0,NaN,NaN,10.3
39048,217,정선군,2021-10-30,9.1,4.1,17.8,NaN,4.2,74.9,NaN,NaN,10.7
39049,217,정선군,2021-10-31,9.1,3.3,19.4,NaN,5.1,79.5,NaN,NaN,10.5

In [21]:
gw_group = gw.groupby(['일시']).mean()

In [26]:
gw_group

,지점,평균기온(°C),최저기온(°C),최고기온(°C),일강수량(mm),평균 이슬점온도(°C),평균 상대습도(%),합계 일사량(MJ/m2),일 최심적설(cm),평균 지면온도(°C)
일시,,,,,,,,,,
2014-01-01,137.846154,3.630769,-0.330769,6.361538,0.000000,-7.784615,45.400000,6.922000,2.066667,0.130769
2014-01-02,137.846154,0.823077,-3.961538,6.284615,0.000000,-11.400000,43.800000,8.726000,2.150000,-0.376923
2014-01-03,137.846154,1.546154,-3.538462,7.123077,0.000000,-8.023077,54.346154,5.204000,1.000000,-0.253846
2014-01-04,137.846154,-0.623077,-4.423077,3.584615,7.857143,-3.561538,81.715385,3.554000,4.900000,-0.815385
2014-01-05,137.846154,-0.684615,-4.369231,3.930769,0.120000,-4.461538,77.515385,5.684000,4.933333,-0.153846
...,...,...,...,...,...,...,...,...,...,...
2021-10-27,134.642857,11.750000,6.600000,18.542857,1.733333,4.835714,67.478571,13.681429,0.000000,12.321429
2021-10-28,134.642857,9.978571,3.550000,18.450000,0.000000,3.435714,68.071429,14.671429,0.000000,10.700000
2021-10-29,134.642857,9.985714,4.328571,18.057143,0.000000,4.614286,73.000000,12.457143,0.000000,10.707143
2021-10-30,134.642857,10.528571,5.671429,17.742857,0.000000,5.507143,74.285714,9.744286,0.000000,10.942857
2021-10-31,134.642857,11.114286,5.614286,18.878571,0.175000,6.121429,74.878571,11.650000,0.000000,11.421429

In [25]:
gw_group.info()

<class 'pandas.core.frame.DataFrame'>
DatetimeIndex: 2861 entries, 2014-01-01 to 2021-10-31
Data columns (total 10 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   지점             2861 non-null   float64
 1   평균기온(°C)       2861 non-null   float64
 2   최저기온(°C)       2861 non-null   float64
 3   최고기온(°C)       2861 non-null   float64
 4   일강수량(mm)       2861 non-null   float64
 5   평균 이슬점온도(°C)   2861 non-null   float64
 6   평균 상대습도(%)     2861 non-null   float64
 7   합계 일사량(MJ/m2)  2861 non-null   float64
 8   일 최심적설(cm)     2861 non-null   float64
 9   평균 지면온도(°C)    2861 non-null   float64
dtypes: float64(10)
memory usage: 245.9 KB

In [24]:
gw_group.fillna(0,inplace=True)