In [2]:
import pandas as pd
import numpy as np

# 배추 - 도매시장

In [3]:
cab = pd.read_excel('배추.xlsx', parse_dates=['일자'])

In [4]:
cab

               일자  도매시장        법인    부류  품목       출하지  물량(kg)    금액(원)
0      2021-04-26  서울가락   동화청과(주)  엽경채류  배추  경상남도 합천군   140.0   541400
1      2021-04-26  서울가락   동화청과(주)  엽경채류  배추  경상북도 김천시  2060.0  8204000
2      2021-04-24  서울가락   농협가락(공)  엽경채류  배추  충청남도 당진군    54.0   145500
3      2021-04-20  서울가락   동화청과(주)  엽경채류  배추  경상남도 합천군   102.0   387600
4      2021-04-20  서울가락   동화청과(주)  엽경채류  배추  경상북도 김천시  1780.0  7625500
...           ...   ...       ...   ...  ..       ...     ...      ...
202373 2021-09-13    강릉  (주)강릉농산물  엽경채류  배추   강원도 강릉시  1940.0  2397300
202374 2021-09-13    강릉  (주)강릉농산물  엽경채류  배추   강원도 정선군  3175.0  2535000
202375 2021-09-13    강릉  (주)강릉농산물  엽경채류  배추   강원도 태백시  2913.0  4004200
202376 2021-09-13    강릉  (주)강릉농산물  엽경채류  배추   경기도 이천시    24.0   420000
202377 2021-09-13    강릉  (주)강릉농산물  엽경채류  배추   강원도 평창군  1670.0  1308000

[202378 rows x 8 columns]

In [5]:
cab.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 202378 entries, 0 to 202377
Data columns (total 8 columns):
 #   Column  Non-Null Count   Dtype
---  ------  --------------   -----
 0   일자      202378 non-null  datetime64[ns]
 1   도매시장    202378 non-null  object
 2   법인      202377 non-null  object
 3   부류      202378 non-null  object
 4   품목      202378 non-null  object
 5   출하지     202378 non-null  object
 6   물량(kg)  202378 non-null  float64
 7   금액(원)   202378 non-null  int64
dtypes: datetime64[ns](1), float64(1), int64(1), object(5)
memory usage: 12.4+ MB

## 법인

In [6]:
cab.drop(columns=['법인'], axis=1, inplace=True)

## 출하지

In [10]:
cab['출하지'].unique()

array(['경상남도 합천군', '경상북도 김천시', '충청남도 당진군', '경상남도 밀양시', '충청남도 보령시',
       '경상남도 하동군', '강원도 평창군', '경기도 하남시', '경기도 양평군', '충청남도 서천군', '강원도 횡성군',
       '경상남도', '전라남도 해남군', '경상남도 진주시', '전라남도 진도군', '전라남도 무안군', '충청남도 부여군',
       '경상남도 남해군', '경기도 남양주시', '경상북도 의성군', '전라남도 나주시', '전라남도 신안군',
       '경상남도 창녕군', '충청남도 태안군', '광주 남구', '강원도 인제군', '경기도 평택시', '충청남도 서산시',
       '경상북도 고령군', '전라북도 순창군', '경기도 안성시', '서울특별시 송파구', '경상북도 안동시',
       '경기도 여주군', '전라남도 장성군', '전라남도 고흥군', '강원도 정선군', '강원도 화천군', '강원도 양양군',
       '강원도 홍천군', '전라북도', '경기도 이천시', '충청북도 충주시', '충청남도 청양군', '전라남도 순천시',
       '전라남도 보성군', '충청남도 예산군', '경상북도 문경시', '강원도 양구군', '전라남도 광양시',
       '충청북도 제천시', '전라남도 곡성군', '충청남도 논산시', '충청북도 음성군', '경상북도 영양군',
       '제주도 제주시', '충청북도 진천군', '경기도 광주시', '광주광역시', '전라남도 영암군', '전라북도 고창군',
       '전라남도 완도군', '전라남도 강진군', '충청북도 괴산군', '충청북도 청주시', '경상북도 청송군',
       '전라남도 영광군', '전라북도 부안군', '경상남도 양산시', '충청남도 홍성군', '강원도 강릉시',
       '경상남도 창원시 의창(성산)구', '경기도 화성시', '전라남도', '경기도 포천시', '제주도 서귀포시',
       '충청북도 청원군', '충청남도 공주시', '대전광역시 유성구', '경상남도 김해시', '경상남도 고성군',
       '전라남도 구례군', '충청남도 금산군', '제주도', '경상남도 함양군', '광주광역시 광산구', '경상북도 영덕군',
       '강원도 영월군', '경상북도 칠곡군', '강원도 원주시', '경기도', '대구광역시 수성구', '강원도 태백시',
       '강원도 철원군', '강원도 삼척시', '서울특별시 양천구', '충청남도 아산시', '전라남도 화순군',
       '경기도 용인시', '대구 동구', '서울특별시 동대문구', '경상북도 상주시', '경상북도 봉화군',
       '경상북도 경산시', '강원도 춘천시', '경기도 연천군', '전라북도 익산시', '충청북도 단양군',
       '전라북도 무주군', '서울특별시', '경기도 파주시', '전라북도 진안군', '전라북도 정읍시', '경상남도 의령군',
       '서울특별시 강동구', '강원도', '경상남도 함안군', '전라북도 남원시', '경상남도 거창군', '전라남도 함평군',
       '전라북도 김제시', '충청남도 천안시', '전라북도 완주군', '경상북도', '경상북도 영주시', '충청북도',
       '경상북도 예천군', '충청북도 보은군', '경상남도 산청군', '광주 서구', '전라남도 담양군', '경기도 가평군',
       '경상북도 포항시', '전라남도 목포시', '서울특별시 도봉구', '경상북도 청도군', '경상북도 구미시',
       '대전 동구', '서울특별시 서대문구', '경기도 고양시', '전라북도 임실군', '강원도 고성군',
       '경상북도 울진군', '충청북도 영동군', '충청남도', '경상북도 경주시', '경기도 양주시', '부산 남구',
       '경기도 김포시', '강원도 속초시', '세종시 세종시', '대전광역시', '전라북도 군산시', '전라북도 장수군',
       '울산광역시 울주군', '대구 북구', '서울특별시 강남구', '전라남도 장흥군', '경기도 동두천시',
       '경기도 광명시', '충청북도 증평군', '서울 강서구', '인천광역시 계양구', '부산광역시 부산진구',
       '광주 동구', '울산 북구', '광주 북구', '대전 서구', '경기도 수원시', '울산 중구', '경상북도 군위군',
       '서울특별시 관악구', '대구광역시 달서구', '경기도 안양시', '전라북도 전주시', '부산 북구', '울산 동구',
       '경기도 부천시', '경기도 성남시', '서울특별시 성동구', '서울특별시 강북구', '대구광역시 달성군',
       '대전광역시 대덕구', '서울특별시 중랑구', '대구 남구', '경기도 오산시', '서울특별시 노원구', '인천 중구',
       '경기도 시흥시', '경기도 의왕시', '전라남도 여수시', '경기도 안산시', '경기도 군포시', '대구광역시',
       '인천광역시', '부산광역시', '경기도 구리시', '서울특별시 은평구', '경기도 의정부시', '서울특별시 종로구',
       '강원도 동해시', '경상북도 영천시', '인천광역시 남동구', '경기도 과천시', '인천 서구',
       '인천광역시 강화군', '충청북도 옥천군', '인천광역시 연수구', '부산 동구', '인천광역시 옹진군',
       '인천 남구', '인천광역시 부평구', '인천 동구', '서울특별시 서초구', '부산광역시 사상구',
       '부산광역시 사하구', '부산광역시 수영구', '경상남도 사천시', '부산광역시 금정구', '부산 서구',
       '경상북도 성주군', '부산 중구', '대구 중구', '서울특별시 마포구', '경상남도 통영시', '대전 중구',
       '충청남도 계룡시', '세종시', '부산 강서구', '울산광역시', '대구 서구', '서울특별시 동작구',
       '경상남도 창원시 마산회원구', '경상북도 울릉군', '경상남도 거제시', '부산광역시 기장군', '서울 중구',
       '경상남도 진해시', '부산광역시 해운대구', '울산 남구'], dtype=object)

In [8]:
drop_index = cab[(cab['출하지'] == '-')|(cab['출하지'] == '수입산')].index
cab.drop(index = drop_index, axis=0, inplace=True)

In [9]:
name_split = cab['출하지'].str.split(" ")

In [11]:
cab['출하지'] = name_split.str.get(0)

In [12]:
cab['출하지'].replace('광주','광주광역시',inplace=True)
cab['출하지'].replace('대구','대구광역시',inplace=True)
cab['출하지'].replace('대전','대전광역시',inplace=True)
cab['출하지'].replace('부산','부산광역시',inplace=True)
cab['출하지'].replace('서울','서울특별시',inplace=True)
cab['출하지'].replace('울산','울산광역시',inplace=True)
cab['출하지'].replace('인천','인천광역시',inplace=True)

In [13]:
cab['출하지'].unique()

array(['경상남도', '경상북도', '충청남도', '강원도', '경기도', '전라남도', '광주광역시', '전라북도',
       '서울특별시', '충청북도', '제주도', '대전광역시', '대구광역시', '부산광역시', '세종시', '울산광역시',
       '인천광역시'], dtype=object)

## 금액/물량

In [14]:
cab[(cab['금액(원)'] <= 0)|(cab['물량(kg)'] <=0)]

               일자  도매시장    부류  품목    출하지  물량(kg)   금액(원)
825    2021-02-26  서울가락  엽경채류  배추   전라남도     0.0       0
1383   2021-03-17  서울가락  엽경채류  배추    강원도     0.0 -414000
1529   2021-02-19  서울가락  엽경채류  배추   전라남도     0.0       0
1689   2021-03-25  서울가락  엽경채류  배추   전라남도     0.0 -400000
2029   2019-06-21  서울가락  엽경채류  배추  대구광역시     0.0 -308000
...           ...   ...   ...  ..    ...     ...     ...
201372 2020-07-06    강릉  엽경채류  배추    강원도    72.0 -236000
201728 2019-06-06    강릉  엽경채류  배추    강원도  -230.0  -39100
202173 2019-01-29    강릉  엽경채류  배추  서울특별시    -6.0    6000
202352 2021-06-17    강릉  엽경채류  배추    경기도   -14.0   -4000
202363 2021-08-30    강릉  엽경채류  배추    경기도    -2.0  371000

[442 rows x 7 columns]

In [15]:
drop_index2 = cab[(cab['금액(원)'] <= 0)|(cab['물량(kg)'] <=0)].index
cab.drop(index= drop_index2, axis=0, inplace=True)

## 단위당금액

In [16]:
cab['단위당금액'] = round(cab['금액(원)']/cab['물량(kg)'],0)

In [17]:
cab['단위당금액'] = cab['단위당금액'].astype(int)

In [18]:
cab

               일자  도매시장    부류  품목   출하지  물량(kg)    금액(원)  단위당금액
0      2021-04-26  서울가락  엽경채류  배추  경상남도   140.0   541400   3867
1      2021-04-26  서울가락  엽경채류  배추  경상북도  2060.0  8204000   3983
2      2021-04-24  서울가락  엽경채류  배추  충청남도    54.0   145500   2694
3      2021-04-20  서울가락  엽경채류  배추  경상남도   102.0   387600   3800
4      2021-04-20  서울가락  엽경채류  배추  경상북도  1780.0  7625500   4284
...           ...   ...   ...  ..   ...     ...      ...    ...
202373 2021-09-13    강릉  엽경채류  배추   강원도  1940.0  2397300   1236
202374 2021-09-13    강릉  엽경채류  배추   강원도  3175.0  2535000    798
202375 2021-09-13    강릉  엽경채류  배추   강원도  2913.0  4004200   1375
202376 2021-09-13    강릉  엽경채류  배추   경기도    24.0   420000  17500
202377 2021-09-13    강릉  엽경채류  배추   강원도  1670.0  1308000    783

[195560 rows x 8 columns]

## 저장

In [19]:
cab.to_excel('배추_수정.xlsx', index=False)

In [20]:
cab2 = pd.read_excel('배추_수정.xlsx')

In [21]:
cab2

               일자  도매시장    부류  품목   출하지  물량(kg)    금액(원)  단위당금액
0      2021-04-26  서울가락  엽경채류  배추  경상남도   140.0   541400   3867
1      2021-04-26  서울가락  엽경채류  배추  경상북도  2060.0  8204000   3983
2      2021-04-24  서울가락  엽경채류  배추  충청남도    54.0   145500   2694
3      2021-04-20  서울가락  엽경채류  배추  경상남도   102.0   387600   3800
4      2021-04-20  서울가락  엽경채류  배추  경상북도  1780.0  7625500   4284
...           ...   ...   ...  ..   ...     ...      ...    ...
195555 2021-09-13    강릉  엽경채류  배추   강원도  1940.0  2397300   1236
195556 2021-09-13    강릉  엽경채류  배추   강원도  3175.0  2535000    798
195557 2021-09-13    강릉  엽경채류  배추   강원도  2913.0  4004200   1375
195558 2021-09-13    강릉  엽경채류  배추   경기도    24.0   420000  17500
195559 2021-09-13    강릉  엽경채류  배추   강원도  1670.0  1308000    783

[195560 rows x 8 columns]

# 배추 - 소매시장

In [3]:
cab2 = pd.read_excel('배추_소매.xlsx', parse_dates=['날짜'])

In [4]:
cab2

       품목  품종         날짜  지역   평균가격
0      배추   봄 2019-05-21  세종  2,480
1      배추   봄 2019-05-22  세종  2,480
2      배추   봄 2019-05-23  세종  2,480
3      배추   봄 2019-05-24  세종  2,480
4      배추   봄 2019-05-27  세종  2,480
...    ..  ..        ...  ..    ...
11067  배추  월동 2021-05-04  강릉  5,660
11068  배추  월동 2021-05-06  강릉  5,660
11069  배추  월동 2021-05-07  강릉  5,660
11070  배추  월동 2021-05-10  강릉  5,660
11071  배추  월동 2021-05-11  강릉  5,660

[11072 rows x 5 columns]